/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appauditoria;

import com.mycompany.appauditoria.dao.FuncionarioDAO;
import com.mycompany.appauditoria.model.Funcionario;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victo
 */
public class JFConsFuncionario extends javax.swing.JInternalFrame {
    private final String usuarioCpfLogado;
    private final FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
    private final DefaultTableModel tableModel;

    /**
     * Creates new form jFConsFuncionario
     * @param usuarioCpfLogado
     */
    public JFConsFuncionario(String usuarioCpfLogado) {
        this.usuarioCpfLogado = usuarioCpfLogado;
        initComponents();
        tableModel = (DefaultTableModel) jTFuncionario.getModel();
    }
    
    private void listarRegistros() {
        tableModel.setNumRows(0);
        
        try {
            for (Funcionario funcionario : funcionarioDAO.listarTodos()) {
                tableModel.addRow(new Object[]{
                    funcionario.getCpf(),
                    funcionario.getNome(),
                    funcionario.getTelefone(),
                    funcionario.getFuncao()
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(
                this,
                "Erro ao buscar funcionários: " + ex.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBConsultar = new javax.swing.JButton();
        jBAtualizar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFuncionario = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de Funcionário");
        setFrameIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("imgs/person-apron.svg", 20, 20));

        jBConsultar.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("imgs/search.svg", 20, 20));
        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(this::jBConsultarActionPerformed);

        jBAtualizar.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("imgs/autorenew.svg", 20, 20));
        jBAtualizar.setText("Atualizar");
        jBAtualizar.addActionListener(this::jBAtualizarActionPerformed);

        jBExcluir.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("imgs/delete.svg", 20, 20));
        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(this::jBExcluirActionPerformed);

        jTFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Telefone", "Função"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTFuncionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBExcluir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConsultar)
                    .addComponent(jBAtualizar)
                    .addComponent(jBExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
        listarRegistros();
    }//GEN-LAST:event_jBConsultarActionPerformed

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
        if (jTFuncionario.isEditing()) jTFuncionario.getCellEditor().stopCellEditing();
                
        int linha = jTFuncionario.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Por favor, selecione um funcionário na tabela primeiro.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        String cpf = tableModel.getValueAt(linha, 0).toString();
        String nome = tableModel.getValueAt(linha, 1).toString();
        String telefone = tableModel.getValueAt(linha, 2).toString();
        String funcao = tableModel.getValueAt(linha, 3).toString();

        try {
            if (funcionarioDAO.atualizarFuncionario(new Funcionario(cpf, nome, telefone, funcao), usuarioCpfLogado)) {
                JOptionPane.showMessageDialog(
                    this,
                    "Funcionário atualizado com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Funcionário não encontrado.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
                );
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                this,
                ex.getMessage(),
                "Dados inválidos",
                JOptionPane.WARNING_MESSAGE
            );
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(
                this,
                "Erro ao atualizar funcionário: " + ex.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }

        listarRegistros();
    }//GEN-LAST:event_jBAtualizarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        int linha = jTFuncionario.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Por favor, selecione um funcionário na tabela primeiro.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int confirmacao = JOptionPane.showConfirmDialog(
            this,
            "Tem certeza que deseja excluir " + tableModel.getValueAt(linha, 1).toString() + "?",
            "Confirmar Exclusão",
            JOptionPane.YES_NO_OPTION
        );
        if (confirmacao != JOptionPane.YES_OPTION) return;
        
        try {
            if (funcionarioDAO.deletarFuncionario(tableModel.getValueAt(linha, 0).toString(), usuarioCpfLogado)) {
                JOptionPane.showMessageDialog(
                    this,
                    "Funcionário excluído com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Funcionário não encontrado.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
                );
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(
                this,
                "Erro ao excluir funcionário: " + ex.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }

        listarRegistros();
    }//GEN-LAST:event_jBExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTFuncionario;
    // End of variables declaration//GEN-END:variables
}
