/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appauditoria;

import com.mycompany.appauditoria.dao.ProdutoDAO;
import com.mycompany.appauditoria.model.Produto;
import java.math.BigDecimal;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victo
 */
public class JFConsProduto extends javax.swing.JInternalFrame {
    private final String usuarioCpfLogado;
    private final ProdutoDAO produtoDAO = new ProdutoDAO();
    private final DefaultTableModel tableModel;
    
    /**
     * Creates new form jFConsProduto
     * @param usuarioCpfLogado
     */
    public JFConsProduto(String usuarioCpfLogado) {
        this.usuarioCpfLogado = usuarioCpfLogado;
        initComponents();
        tableModel = (DefaultTableModel) jTProduto.getModel();
    }
    
    private void listarRegistros() {
        tableModel.setNumRows(0);
        
        try {
            for (Produto produto : produtoDAO.listarTodos()) {
                tableModel.addRow(new Object[]{
                    produto.getCodigo(),
                    produto.getDescricao(),
                    produto.getValor(),
                    produto.getEstoque()
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(
                this,
                "Erro ao buscar produtos: " + ex.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBConsultar = new javax.swing.JButton();
        jBAtualizar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProduto = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de Produto");
        setFrameIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("imgs/package.svg", 20, 20));

        jBConsultar.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("imgs/search.svg", 20, 20));
        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(this::jBConsultarActionPerformed);

        jBAtualizar.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("imgs/autorenew.svg", 20, 20));
        jBAtualizar.setText("Atualizar");
        jBAtualizar.addActionListener(this::jBAtualizarActionPerformed);

        jBExcluir.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("imgs/delete.svg", 20, 20));
        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(this::jBExcluirActionPerformed);

        jTProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Descrição", "Valor", "Estoque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTProduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBExcluir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConsultar)
                    .addComponent(jBAtualizar)
                    .addComponent(jBExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
        listarRegistros();
    }//GEN-LAST:event_jBConsultarActionPerformed

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
        if (jTProduto.isEditing()) jTProduto.getCellEditor().stopCellEditing();
        
        int linha = jTProduto.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Por favor, selecione um produto na tabela primeiro.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        String codigo = tableModel.getValueAt(linha, 0).toString();
        String descricao = tableModel.getValueAt(linha, 1).toString();
        BigDecimal valor = new BigDecimal(tableModel.getValueAt(linha, 2).toString());
        Integer estoque = Integer.valueOf(tableModel.getValueAt(linha, 3).toString());
        
        try {
            if (produtoDAO.atualizarProduto(new Produto(codigo, descricao, valor, estoque), usuarioCpfLogado)) {
                JOptionPane.showMessageDialog(
                    this,
                    "Produto atualizado com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Produto não encontrado.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
                );
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                this,
                ex.getMessage(),
                "Dados inválidos",
                JOptionPane.WARNING_MESSAGE
            );
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(
                this,
                "Erro ao atualizar produto: " + ex.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }
        
        listarRegistros();
    }//GEN-LAST:event_jBAtualizarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        int linha = jTProduto.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Por favor, selecione um produto na tabela primeiro.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        int confirmacao = JOptionPane.showConfirmDialog(
            this,
            "Tem certeza que deseja excluir " + tableModel.getValueAt(linha, 1).toString() + "?",
            "Confirmar Exclusão",
            JOptionPane.YES_NO_OPTION
        );
        if (confirmacao != JOptionPane.YES_OPTION) return;
        
        try {
            if (produtoDAO.deletarProduto(tableModel.getValueAt(linha, 0).toString(), usuarioCpfLogado)) {
                JOptionPane.showMessageDialog(
                    this,
                    "Produto excluído com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Produto não encontrado.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
                );
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(
                this,
                "Erro ao excluir produto: " + ex.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
        }
        
        listarRegistros();
    }//GEN-LAST:event_jBExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTProduto;
    // End of variables declaration//GEN-END:variables
}
