/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appauditoria;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author victo
 */
public class JFMain extends javax.swing.JFrame {
    private final String usuarioCpfLogado;
    
    // Configura o tema inicial da tela
    private void configurarTema() {
        boolean isDark = UIManager.getLookAndFeel() instanceof FlatDarkLaf;
        jRTema.setSelected(isDark);
        if (isDark) {
            jRTema.setIcon(new FlatSVGIcon("imgs/dark-mode.svg", 20, 20));
            jRTema.setText("Tema Escuro");
        } else {
            jRTema.setIcon(new FlatSVGIcon("imgs/light-mode.svg", 20, 20));
            jRTema.setText("Tema Claro");
        }

    }

    /**
     * Creates new form jFMain
     *
     * @param perfilId
     * @param usuarioCpfLogado
     */
    public JFMain(Integer perfilId, String usuarioCpfLogado) {
        this.usuarioCpfLogado = usuarioCpfLogado;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        configurarTema();

        switch (perfilId) {
            case 1 -> {
                // jMCadProduto.setVisible(false);
                // jMConsProduto.setVisible(false);
            }
            case 2 -> {
                jMCadGerente.setVisible(false);
                jMConsGerente.setVisible(false);
            }
            case 3 -> {
                jMCadGerente.setVisible(false);
                jMConsGerente.setVisible(false);
            }

            default ->
                throw new AssertionError();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDMenu = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRTema = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMCadProduto = new javax.swing.JMenuItem();
        jMCadFuncionario = new javax.swing.JMenuItem();
        jMCadGerente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMConsProduto = new javax.swing.JMenuItem();
        jMConsFuncionario = new javax.swing.JMenuItem();
        jMConsGerente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/imgs/logo.png")).getImage());

        javax.swing.GroupLayout jDMenuLayout = new javax.swing.GroupLayout(jDMenu);
        jDMenu.setLayout(jDMenuLayout);
        jDMenuLayout.setHorizontalGroup(
            jDMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDMenuLayout.setVerticalGroup(
            jDMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Arquivo");

        jRTema.setSelected(true);
        jRTema.addActionListener(this::jRTemaActionPerformed);
        jMenu1.add(jRTema);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastro");

        jMCadProduto.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("imgs/package.svg", 20, 20));
        jMCadProduto.setText("Produto");
        jMCadProduto.setToolTipText("");
        jMCadProduto.addActionListener(this::jMCadProdutoActionPerformed);
        jMenu2.add(jMCadProduto);

        jMCadFuncionario.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("imgs/person-apron.svg", 20, 20));
        jMCadFuncionario.setText("Funcionário");
        jMCadFuncionario.addActionListener(this::jMCadFuncionarioActionPerformed);
        jMenu2.add(jMCadFuncionario);

        jMCadGerente.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("imgs/manage-accounts.svg", 20, 20));
        jMCadGerente.setText("Gerente");
        jMCadGerente.addActionListener(this::jMCadGerenteActionPerformed);
        jMenu2.add(jMCadGerente);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consulta");

        jMConsProduto.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("imgs/package.svg", 20, 20));
        jMConsProduto.setText("Produto");
        jMConsProduto.addActionListener(this::jMConsProdutoActionPerformed);
        jMenu3.add(jMConsProduto);

        jMConsFuncionario.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("imgs/person-apron.svg", 20, 20));
        jMConsFuncionario.setText("Funcionário");
        jMConsFuncionario.addActionListener(this::jMConsFuncionarioActionPerformed);
        jMenu3.add(jMConsFuncionario);

        jMConsGerente.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("imgs/manage-accounts.svg", 20, 20));
        jMConsGerente.setText("Gerente");
        jMConsGerente.addActionListener(this::jMConsGerenteActionPerformed);
        jMenu3.add(jMConsGerente);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadProdutoActionPerformed
        JFCadProduto cadProduto = new JFCadProduto(usuarioCpfLogado);
        jDMenu.add(cadProduto);
        cadProduto.setVisible(true);
    }//GEN-LAST:event_jMCadProdutoActionPerformed

    private void jMCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadFuncionarioActionPerformed
        JFCadFuncionario cadFuncionario = new JFCadFuncionario(usuarioCpfLogado);
        jDMenu.add(cadFuncionario);
        cadFuncionario.setVisible(true);
    }//GEN-LAST:event_jMCadFuncionarioActionPerformed

    private void jMCadGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadGerenteActionPerformed
        JFCadGerente cadGerente = new JFCadGerente(usuarioCpfLogado);
        jDMenu.add(cadGerente);
        cadGerente.setVisible(true);
    }//GEN-LAST:event_jMCadGerenteActionPerformed

    private void jMConsProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsProdutoActionPerformed
        JFConsProduto consProduto = new JFConsProduto(usuarioCpfLogado);
        jDMenu.add(consProduto);
        consProduto.setVisible(true);
    }//GEN-LAST:event_jMConsProdutoActionPerformed

    private void jMConsFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsFuncionarioActionPerformed
        JFConsFuncionario consFuncionario = new JFConsFuncionario(usuarioCpfLogado);
        jDMenu.add(consFuncionario);
        consFuncionario.setVisible(true);
    }//GEN-LAST:event_jMConsFuncionarioActionPerformed

    private void jMConsGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsGerenteActionPerformed
        JFConsGerente consGerente = new JFConsGerente(usuarioCpfLogado);
        jDMenu.add(consGerente);
        consGerente.setVisible(true);
    }//GEN-LAST:event_jMConsGerenteActionPerformed

    private void jRTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRTemaActionPerformed
        if (jRTema.isSelected()) {
            jRTema.setText("Tema Escuro");
            jRTema.setIcon(new FlatSVGIcon("imgs/dark-mode.svg", 20, 20));
            FlatDarkLaf.setup();
            FlatSVGIcon.ColorFilter.getInstance().add(Color.BLACK, Color.WHITE);
        } else {
            jRTema.setText("Tema Claro");
            jRTema.setIcon(new FlatSVGIcon("imgs/light-mode.svg", 20, 20));
            FlatLightLaf.setup();
            FlatSVGIcon.ColorFilter.getInstance().add(Color.BLACK, Color.BLACK);
        }

        FlatLaf.updateUI();
    }//GEN-LAST:event_jRTemaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDMenu;
    private javax.swing.JMenuItem jMCadFuncionario;
    private javax.swing.JMenuItem jMCadGerente;
    private javax.swing.JMenuItem jMCadProduto;
    private javax.swing.JMenuItem jMConsFuncionario;
    private javax.swing.JMenuItem jMConsGerente;
    private javax.swing.JMenuItem jMConsProduto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRTema;
    // End of variables declaration//GEN-END:variables
}
