/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.appauditoria;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author victo
 */
public class JPTemaToggle extends javax.swing.JPanel {
    private void configurarEstadoInicial() {
        boolean isDark = UIManager.getLookAndFeel() instanceof FlatDarkLaf;
        jTTema.setSelected(isDark);
        
        jTTema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTTema.setFocusPainted(false);
    }
    
    /**
     * Creates new form JPTemaToggle
     */
    public JPTemaToggle() {
        initComponents();
        configurarEstadoInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTTema = new javax.swing.JToggleButton();

        jTTema.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("imgs/light-mode.svg", 20, 20));
        jTTema.setSelectedIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("imgs/dark-mode.svg", 20, 20));
        jTTema.addActionListener(this::jTTemaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTTema, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTTema, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTemaActionPerformed
        if (jTTema.isSelected()) {
            FlatDarkLaf.setup();
            FlatSVGIcon.ColorFilter.getInstance().add(Color.BLACK, Color.WHITE);
        } else {
            FlatLightLaf.setup();
            FlatSVGIcon.ColorFilter.getInstance().add(Color.BLACK, Color.BLACK);
        }

        FlatLaf.updateUI();
    }//GEN-LAST:event_jTTemaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jTTema;
    // End of variables declaration//GEN-END:variables
}
